struct song_node * table[27];
struct song_node * add_node(struct song_node * t[27],struct song_node * ll);
struct song_node * song_search(char n[100], char a[100]);
struct song_node * artist_search(char a[100]);
struct song_node * list_letter(char letter);
struct song_node * list_artist(char a[100]);
void print_lib(struct song_node * t[27]);
struct song_node * shuffle(struct song_node * t[27]);
struct song_node * delete_song(struct song_node * t[27]);
void clear_lib(struct song_node * t[27]);
